## Multi-class vs Multi-Label Problem

In [1]:
from fastai.vision.all import *

### Multi-class (Single-Label)

In [11]:
activations = torch.randn((4,3))*2
targets = tensor([1, 0, 1, 2])
activations, targets

(tensor([[ 0.5819, -0.8310, -1.6839],
         [ 1.0222, -1.3073,  2.6943],
         [ 0.8619, -1.8743, -2.7649],
         [ 2.1368,  2.7871, -2.7200]]),
 tensor([1, 0, 1, 2]))

In [12]:
# Cross Entropy Loss (softmax -> negative log likelihood loss)
sm_numbers = torch.log_softmax(activations, dim=1)
negative_log_loss = F.nll_loss(sm_numbers, targets, reduction='none')
negative_log_loss.mean()

tensor(3.0809)

In [16]:
# PyTorch style
nn.CrossEntropyLoss()(activations, targets), \
    F.cross_entropy(activations, targets)

(tensor(3.0809), tensor(3.0809))

### Multi-Label

In [21]:
activations = torch.randn((4,3))*2
targets = tensor([
    [1, 0, 0], 
    [0, 1, 0],
    [1, 0, 1],
    [0, 1, 1]]).float()
activations, targets

(tensor([[ 1.4382,  0.3267, -2.3964],
         [-0.1018, -0.5655,  3.1815],
         [ 0.4228,  1.4298, -1.4083],
         [-1.2569,  1.5567,  0.3578]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [1., 0., 1.],
         [0., 1., 1.]]))

In [22]:
# Binary Cross Entropy Loss (sigmoid -> delta_props -> -log)
sm_numbers = activations.sigmoid()
delta_props = torch.where(targets==1, sm_numbers, 1-sm_numbers)
-delta_props.log().mean()

tensor(0.8999)

In [25]:
# PyTorch style
nn.BCEWithLogitsLoss()(activations, targets), \
    F.binary_cross_entropy_with_logits(activations, targets)

(tensor(0.8999), tensor(0.8999))

In [32]:
F.nll_loss?

In [38]:
-math.log(.71)

0.342490308946776

In [39]:
F.nll_loss(tensor([[.71],]).log(),tensor([0])) 

tensor(0.3425)